// global variables
var random_result;
var lost = 0;
var win = 0;
var previous = 0;

var startAndReset = function () 
{

  $(".crystals").empty();

  var images =
  [
    "blueCrystal.jpg",
    "clearCrystal.jpg", 
    "pinkCrystal.jpg", 
    "purpleCrystal.jpg"
  ]; 


// create random number generated by computer
  random_result = Math.floor(Math.random() * 69 ) + 30;
  console.log(random_result);

  $("#result").html(random_result);


// create 4 crystals and random values from 1-10

  for(var i = 0; i < 4; i++)
  {
    var random = Math.floor(Math.random() * 11) + 1;
    console.log(random);

    var crystal = $("<div>");
      crystal.attr({
        "class": 'crystal',
        "data-random": random,
      });
      // crystal.css('background-image', 'url("./images/"' + images[i] + ')' );
    var crystalImg = $("<img>");
    crystalImg.attr({
      'src' : './images/' + images[i],
      'class' : 'crystalImg'
    })

    crystal.append(crystalImg);
    $(".crystals").append(crystal);
  }

  $("#Previous").html(previous);


}

startAndReset();

var reset = function () 
{

}

// make crystals clickable, assign 1-10 value to them
$(document).on('click', '.crystal', function()
{
var num = parseInt($(this).attr('data-random'));

previous += num;
// console.log(previous);

$("#Previous").html(previous);
console.log(previous);


// if your number > comp number, 1 loss is added and game resets
if (previous > random_result) 
{
  lost++; 
  $(".lost").html("losses: " + lost); 
  console.log("you lost!");
  previous = 0;
  alert("you lost")

  startAndReset();
}

// if your number = comp number, 1 win is added and game resets

else if (previous === random_result) 
{
  win++; 
  $(".win").html("wins: " + win);
  previous = 0;
  alert("you won!")
  console.log("you won!");
  startAndReset();
}

});


